language: R
sudo: required
cache: packages
warnings_are_errors: true
before_install:
  - printf "url: https://cds.climate.copernicus.eu/api/v2\nkey: %s:%s" ${CDSAPIUSER} ${CDSAPIRC} > ~/.cdsapirc

r:
  - release

